name: markdown
version: 7.0.0-dev

description: A portable Markdown library written in Dart that can parse
 Markdown into HTML.
repository: https://github.com/dart-lang/markdown

executables:
  markdown:

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.2
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  build_version: ^2.1.1
  build_web_compilers: ^4.0.5
  collection: ^1.17.1
  html: ^0.15.4
  http: ^1.1.0
  io: ^1.0.4
  js: ^0.6.7
  lints: ^2.1.1
  path: ^1.8.3
  pool: ^1.5.1
  tar: ^0.5.6
  yaml: ^3.1.2
