name: markdown
version: 7.0.0-dev

description: A portable Markdown library written in Dart that can parse
 Markdown into HTML.
repository: https://github.com/dart-lang/markdown

executables:
  markdown:

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.4.1
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.4
  build_version: ^2.1.1
  build_web_compilers: ^4.0.3
  collection: ^1.17.2
  html: ^0.15.3
  http: ^1.0.0
  io: ^1.0.4
  js: ^0.6.8
  lints: ^2.1.0
  path: ^1.8.3
  pool: ^1.5.1
  tar: ^0.5.6
  test: ^1.24.3
  yaml: ^3.1.2
